name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner - comment
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Create credentials file
      #   run: |
      #     echo "${{ secrets.GOOGLE_CREDENTIALS }}" > google-credentials.json

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/inlaid-goods-451523-i3/poc-api/poc-api:latest .
          docker push  us-central1-docker.pkg.dev/inlaid-goods-451523-i3/poc

      # - name: Build Docker image
      #   run: |
      #     docker build -t poc-api-docker .

      # - name: list docker images
      #   run: docker images

      # - name: docker login
      #   run: cat google-credentials.json | docker login -u _json_key_base64 --password-stdin \ https://us-central1-docker.pkg.dev/inlaid-goods-451523-i3/poc-api
      




